In [88]:
import numpy as np 
from Environment import Easy21
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_value_function1(Value):
  
    val = np.transpose(Value)
    _x = np.arange(1,11,1)
    _y = np.arange(1,22)
    _xx, _yy = np.meshgrid(_x, _y)
   
    x, y = _xx.ravel(), _yy.ravel()
   
    fig = plt.figure()
    ax = Axes3D(fig)
    ax.plot_surface(_xx, _yy, val, rstride=1, cstride=1)

    plt.show()
    
def plot_value_function2(Value):
    fig = plt.figure(figsize=(8, 8))
    ax1 = fig.add_subplot(111, projection='3d')

    _x = np.arange(1,11,1)
    _y = np.arange(1,22)
    _xx, _yy = np.meshgrid(_x, _y)
    top =  Value.reshape(-1)
    x, y = _xx.ravel(), _yy.ravel()
   
    bottom = np.zeros_like(top)
    width = depth = 1

    
    ax1.bar3d(x, y, bottom, width, depth, top, shade=True)
    ax1.set_title('Value Function')
    
    plt.show()
    
def get_value(action_value):
    Value = np.zeros((10,21))
    for i in range(len(Value)):
        for j in range(len(Value[0])):
            Value[i,j] = np.amin(action_value[i,j])
    return Value



In [131]:
action_value = np.array([[[0,0] for i in range(-10,22)] for j in range(10)])

N0 = 100
iterations = 1000
actions = ["Hit", "Stick"]
number_action_value = np.array([[[0,0] for i in range(-10,22)] for j in range(10)])

for it in range(iterations):
    game = Easy21()
    states = [game.state]
    Gt = 0
    
    while game.isTerminal == False:
        last_state = states[-1]
        dealer, player_sum = last_state["dealer"], last_state["player_sum"]
        action_value_ij = action_value[dealer-1, player_sum+10]
        epsilon_t = N0 / (N0 + sum(number_action_value[dealer-1, player_sum+10,:]) )
        
        p = np.random.binomial(1,epsilon_t)
        if p == 0:
            index_action = np.argmax(action_value_ij)
        
        else:
            index_action = np.argmin(action_value_ij)
        pick_action = actions[index_action]
        number_action_value[dealer-1, player_sum+10, index_action]+=1
        state,reward = game.step(pick_action)
        states.append(state)
        Gt+=reward
        
    """episode ended"""
    for i in range(-10,22):
        for j in range(10):
            for action in [0,1]:
                if  number_action_value[j, i+10, action]!=0:
                    action_value[j, i+10, action] +=  (Gt - action_value[j, i+10, action] ) / number_action_value[j, i+10, action]
            
#plot_value_function2(get_value(number_action_value))
print(action_value)

[[[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [-1  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [-1  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 